fix-import-issue
ow2-proactive/scheduling-portal pull request #740
Opened 2022-04-27 14:42 UTC by oanaBiancaSchiopu

2022-04-27 14:46 UTC, mboussaa commented on scheduler-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/scheduler/client/SubmitWindow.java
> +                String selectedWorkflowLabel = workflowsListBox.getSelectedValue().substring(
```workflowsListBox.getSelectedValue().substring(workflowsListBox.getSelectedValue().indexOf(" - ").trim()```

2022-04-27 14:48 UTC, mboussaa commented on scheduler-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/scheduler/client/SubmitWindow.java
> +                String selectedWorkflowLabel = workflowsListBox.getSelectedValue().substring(
and this is wrong if the project name contains one or many ```-```. Same for WF name

2022-04-27 14:49 UTC, mboussaa requested changes
to fix

2022-04-27 14:51 UTC, mboussaa commented on scheduler-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/scheduler/client/SubmitWindow.java
> +                String selectedWorkflowLabel = workflowsListBox.getSelectedValue().substring(
And finally, we should investigate the dropdown list with columns

2022-04-28 10:18 UTC, mboussaa commented on scheduler-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/scheduler/client/SubmitWindow.java
> +                LogModel.getInstance().logCriticalMessage("selectedWorkflowLabel: " + selectedWorkflowLabel);
why critical ?

2022-04-28 10:21 UTC, mboussaa approved these changes

2022-04-28 10:24 UTC, oanaBiancaSchiopu commented on scheduler-portal/src/main/java/org/ow2/proactive_grid_cloud_portal/scheduler/client/SubmitWindow.java
> +                LogModel.getInstance().logCriticalMessage("selectedWorkflowLabel: " + selectedWorkflowLabel);
I will delete this

2022-04-28 13:07 UTC, AlexFalessi approved these changes

2022-04-28 13:46 UTC, merged